export type Internship = {
  id: string;
  title: string;
  projectTitle: string;
  domain: string;
  duration: string;
  level: string;
  originalPrice: number;
  price: number;
  tasks: string[];
  includes: string[];
  description: string;
  iconName: string;
  weeklyTasks: WeeklyTask[];
};

export type WeeklyTask = {
  week: number;
  title: string;
  type: string;
  estimatedTime: string;
  description: string;
  steps: string[];
  resources?: string[];
  example?: string;
};

export const internships: Internship[] = [
  {
    id: "frontend-developer-internship",
    title: "Frontend Developer Internship",
    projectTitle: "Build Netflix Clone",
    domain: "Web Development",
    duration: "4 Weeks",
    level: "Beginner Friendly",
    originalPrice: 49900,
    price: 34900,
    iconName: "Code2",
    tasks: [
      "Create responsive streaming platform UI",
      "Build reusable React components",
      "Integrate real movie API",
      "Deploy production-ready app",
    ],
    includes: ["Project source code", "Mentor review", "Deployment guide", "Verified certificate"],
    description: "Build real-world frontend projects that strengthen your portfolio and recruiter visibility.",
    weeklyTasks: [
      { week: 1, title: "UI Foundations", type: "Development", estimatedTime: "4-5 hours", description: "Set up React app and core layout.", steps: ["Project setup", "Build components", "Responsive layout", "Navigation"] },
      { week: 2, title: "Interactive Components", type: "Development", estimatedTime: "4-5 hours", description: "Create cards, sections, and dynamic lists.", steps: ["Card systems", "State handling", "Animations", "UX polish"] },
      { week: 3, title: "API Integration", type: "Integration", estimatedTime: "4-5 hours", description: "Connect API and render dynamic data.", steps: ["Fetch data", "Error states", "Loading states", "Search/filter"] },
      { week: 4, title: "Launch", type: "Deployment", estimatedTime: "3-4 hours", description: "Deploy and optimize performance.", steps: ["Performance checks", "Deploy to Vercel", "Final QA", "Portfolio publish"] },
    ],
  },
  {
    id: "fullstack-developer-internship",
    title: "Full-Stack Developer Internship",
    projectTitle: "Build Twitter Clone",
    domain: "Web Development",
    duration: "4 Weeks",
    level: "Intermediate",
    originalPrice: 49900,
    price: 34900,
    iconName: "Code2",
    tasks: [
      "Build secure authentication",
      "Design scalable backend APIs",
      "Build feed and interactions",
      "Deploy full-stack app",
    ],
    includes: ["Backend boilerplate", "Database setup", "Code reviews", "Verified certificate"],
    description: "Build complete production apps with both frontend and backend architecture.",
    weeklyTasks: [
      { week: 1, title: "Architecture Setup", type: "Backend", estimatedTime: "4-5 hours", description: "Set up app architecture and database.", steps: ["Project scaffolding", "Database schema", "Auth setup", "API structure"] },
      { week: 2, title: "Core Features", type: "Development", estimatedTime: "5-6 hours", description: "Implement post, like, and feed features.", steps: ["Feed API", "Post creation", "Like system", "User profile"] },
      { week: 3, title: "Frontend Flow", type: "Frontend", estimatedTime: "4-5 hours", description: "Connect UI to backend and optimize UX.", steps: ["UI pages", "Client state", "Error handling", "Responsiveness"] },
      { week: 4, title: "Production Deploy", type: "Deployment", estimatedTime: "3-4 hours", description: "Deploy app and run final QA.", steps: ["Deploy backend", "Deploy frontend", "End-to-end test", "Publish"] },
    ],
  },
  {
    id: "ai-engineer-internship",
    title: "AI Engineer Internship",
    projectTitle: "Create ChatGPT-like Chatbot",
    domain: "AI / ML",
    duration: "4 Weeks",
    level: "Intermediate",
    originalPrice: 49900,
    price: 34900,
    iconName: "Cpu",
    tasks: [
      "Integrate LLM APIs",
      "Build conversational UI",
      "Add chat memory",
      "Deploy intelligent assistant",
    ],
    includes: ["Prompt templates", "API integration kit", "Deployment guide", "Verified certificate"],
    description: "Create practical AI applications that showcase real product-building skills.",
    weeklyTasks: [
      { week: 1, title: "AI Foundations", type: "AI", estimatedTime: "4-5 hours", description: "Set up model APIs and prompt structure for reliable outputs.", steps: ["API setup", "Prompt patterns", "Output formatting", "Error handling"] },
      { week: 2, title: "Easy Project Build", type: "Development", estimatedTime: "4-5 hours", description: "Build AI Text / Notes Generator with simple UI.", steps: ["Input form", "Generate notes", "Save output", "Quality checks"] },
      { week: 3, title: "Medium Project Build", type: "Development", estimatedTime: "4-5 hours", description: "Build AI Resume Analyzer with score and feedback.", steps: ["Upload flow", "Prompt scoring", "Feedback sections", "Result layout"] },
      { week: 4, title: "Deployment & Portfolio", type: "Deployment", estimatedTime: "3-4 hours", description: "Deploy app and document your AI project for hiring.", steps: ["Deploy", "Prompt tuning", "Regression test", "Portfolio write-up"] },
    ],
  },
  {
    id: "data-scientist-internship",
    title: "Data Scientist Internship",
    projectTitle: "Build Recommendation Engine",
    domain: "Data Science",
    duration: "4 Weeks",
    level: "Intermediate",
    originalPrice: 49900,
    price: 34900,
    iconName: "Database",
    tasks: [
      "Explore behavior datasets",
      "Train recommendation models",
      "Evaluate model accuracy",
      "Ship ML endpoint",
    ],
    includes: ["Real datasets", "Notebook templates", "Model review", "Verified certificate"],
    description: "Turn raw user data into product decisions with practical machine learning workflows.",
    weeklyTasks: [
      { week: 1, title: "Data Preparation", type: "Analysis", estimatedTime: "4-5 hours", description: "Clean and structure recommendation dataset.", steps: ["Load dataset", "EDA", "Feature prep", "Split strategy"] },
      { week: 2, title: "Modeling", type: "ML", estimatedTime: "4-5 hours", description: "Implement collaborative filtering.", steps: ["Baseline model", "Similarity matrix", "Prediction pipeline", "Validation"] },
      { week: 3, title: "Evaluation", type: "Analysis", estimatedTime: "3-4 hours", description: "Measure precision and ranking quality.", steps: ["Metrics", "Error analysis", "Model comparison", "Report"] },
      { week: 4, title: "Deployment", type: "Deployment", estimatedTime: "3-4 hours", description: "Serve recommendations through API.", steps: ["Model export", "API endpoint", "Load testing", "Docs"] },
    ],
  },
  {
    id: "python-developer-internship",
    title: "Python Developer Internship",
    projectTitle: "Build Automation Scripts Suite",
    domain: "Python",
    duration: "4 Weeks",
    level: "Beginner Friendly",
    originalPrice: 49900,
    price: 34900,
    iconName: "Cpu",
    tasks: [
      "Write script utilities",
      "Automate repetitive workflows",
      "Process data files",
      "Package scripts for reuse",
    ],
    includes: ["Starter templates", "Automation challenges", "Code review", "Verified certificate"],
    description: "Automate common workflows and build practical Python skills for internships and jobs.",
    weeklyTasks: [
      { week: 1, title: "Python Automation Basics", type: "Development", estimatedTime: "4-5 hours", description: "Learn script structure and automation workflows.", steps: ["CLI input", "File operations", "Email basics", "Scheduling"] },
      { week: 2, title: "Easy Project Build", type: "Development", estimatedTime: "4-5 hours", description: "Build Task Automation Script for files and email.", steps: ["Folder automation", "Email trigger", "Logging", "Error handling"] },
      { week: 3, title: "Medium Project Build", type: "Development", estimatedTime: "4-5 hours", description: "Build a CLI Utility Tool (password manager style).", steps: ["Command parser", "Secure storage", "CRUD commands", "Validation"] },
      { week: 4, title: "Packaging & Delivery", type: "Deployment", estimatedTime: "3-4 hours", description: "Package scripts and publish with documentation.", steps: ["Refactor", "Unit checks", "Documentation", "GitHub release"] },
    ],
  },
  {
    id: "uiux-designer-internship",
    title: "UI/UX Designer Internship",
    projectTitle: "Design SaaS Landing in Figma",
    domain: "UI/UX",
    duration: "4 Weeks",
    level: "Beginner Friendly",
    originalPrice: 49900,
    price: 34900,
    iconName: "LineChart",
    tasks: [
      "Create wireframes",
      "Build design system",
      "Prototype interactions",
      "Present case study",
    ],
    includes: ["Figma files", "Design critique", "Case-study template", "Verified certificate"],
    description: "Design user-focused interfaces and turn them into portfolio-grade case studies.",
    weeklyTasks: [
      { week: 1, title: "UX Research & Wireframes", type: "Design", estimatedTime: "3-4 hours", description: "Define users, flows, and low-fidelity wireframes.", steps: ["User goals", "Journey map", "Wireframes", "Flow validation"] },
      { week: 2, title: "Easy Project Build", type: "Design", estimatedTime: "4-5 hours", description: "Design Mobile App UI in Figma.", steps: ["Color system", "Typography", "Components", "Screen design"] },
      { week: 3, title: "Medium Project Build", type: "Design", estimatedTime: "4-5 hours", description: "Create complete app case study with user flow and prototype.", steps: ["User flow", "Clickable prototype", "Usability checks", "Iteration"] },
      { week: 4, title: "Case Study Delivery", type: "Presentation", estimatedTime: "3-4 hours", description: "Finalize portfolio-ready case study and presentation.", steps: ["Case-study write-up", "Before/after rationale", "Export assets", "Portfolio upload"] },
    ],
  },
  {
    id: "flutter-developer-internship",
    title: "Flutter Developer Internship",
    projectTitle: "Build Instagram Clone",
    domain: "Android / Flutter",
    duration: "4 Weeks",
    level: "Intermediate",
    originalPrice: 49900,
    price: 34900,
    iconName: "Code2",
    tasks: [
      "Create cross-platform UI",
      "Integrate Firebase auth",
      "Build feed and upload",
      "Publish app build",
    ],
    includes: ["Flutter starter", "Firebase setup", "Mentor checkpoints", "Verified certificate"],
    description: "Build mobile apps for Android and iOS with one codebase and practical deployment workflow.",
    weeklyTasks: [
      { week: 1, title: "App Foundation", type: "Development", estimatedTime: "4-5 hours", description: "Set up Flutter app and navigation.", steps: ["Project setup", "Routing", "UI shells", "State basics"] },
      { week: 2, title: "Auth & Data", type: "Integration", estimatedTime: "4-5 hours", description: "Implement Firebase auth and storage.", steps: ["Auth flows", "Firestore", "Storage", "Security rules"] },
      { week: 3, title: "Social Features", type: "Development", estimatedTime: "5-6 hours", description: "Build post feed and interactions.", steps: ["Feed screen", "Create post", "Likes/comments", "Profile"] },
      { week: 4, title: "Build & Ship", type: "Deployment", estimatedTime: "3-4 hours", description: "Prepare release builds.", steps: ["QA testing", "Release config", "Export APK/IPA", "Submission checklist"] },
    ],
  },
  {
    id: "android-developer-internship",
    title: "Android Developer Internship",
    projectTitle: "Build Spotify Clone (Kotlin)",
    domain: "Android / Flutter",
    duration: "4 Weeks",
    level: "Beginner Friendly",
    originalPrice: 49900,
    price: 34900,
    iconName: "Code2",
    tasks: [
      "Build native Android UI",
      "Implement media controls",
      "Manage playlists",
      "Release APK",
    ],
    includes: ["Kotlin templates", "Media APIs", "Testing checklist", "Verified certificate"],
    description: "Create native Android applications with production patterns and clean architecture.",
    weeklyTasks: [
      { week: 1, title: "Kotlin + Layouts", type: "Development", estimatedTime: "4-5 hours", description: "Set up app and core screens.", steps: ["Activities/fragments", "Layouts", "Navigation", "State"] },
      { week: 2, title: "Player System", type: "Development", estimatedTime: "4-5 hours", description: "Integrate playback and controls.", steps: ["MediaPlayer", "Queue", "Playback states", "UX handling"] },
      { week: 3, title: "Data Layer", type: "Backend", estimatedTime: "4-5 hours", description: "Persist playlists and preferences.", steps: ["Room DB", "Data models", "Repository", "Testing"] },
      { week: 4, title: "App Release", type: "Deployment", estimatedTime: "3-4 hours", description: "Package and publish APK.", steps: ["Build variants", "QA", "Release notes", "Portfolio publish"] },
    ],
  },
  {
    id: "java-developer-internship",
    title: "Java Developer Internship",
    projectTitle: "Build Student Management System",
    domain: "Java / C++",
    duration: "4 Weeks",
    level: "Beginner Friendly",
    originalPrice: 49900,
    price: 34900,
    iconName: "Code2",
    tasks: [
      "Design OOP model",
      "Build CRUD operations",
      "Add persistence layer",
      "Create reports",
    ],
    includes: ["Java starter kit", "OOP review", "Mini-project rubric", "Verified certificate"],
    description: "Strengthen core Java problem solving and backend fundamentals with practical builds.",
    weeklyTasks: [
      { week: 1, title: "Java Core & OOP", type: "Development", estimatedTime: "4-5 hours", description: "Set up Java architecture and OOP building blocks.", steps: ["Classes", "Encapsulation", "Inheritance", "Interfaces"] },
      { week: 2, title: "Easy Project Build", type: "Development", estimatedTime: "4-5 hours", description: "Build console-based management system.", steps: ["Menu flow", "CRUD actions", "Validation", "Exception handling"] },
      { week: 3, title: "Medium Project Build", type: "Backend", estimatedTime: "4-5 hours", description: "Build basic REST API using Spring Boot.", steps: ["Spring setup", "REST endpoints", "DTO + validation", "Simple persistence"] },
      { week: 4, title: "Testing & Documentation", type: "Deployment", estimatedTime: "3-4 hours", description: "Test modules and publish project documentation.", steps: ["API testing", "Code cleanup", "README", "Project demo"] },
    ],
  },
  {
    id: "cpp-developer-internship",
    title: "C++ Developer Internship",
    projectTitle: "Build DSA Toolkit for Interviews",
    domain: "Java / C++",
    duration: "4 Weeks",
    level: "Intermediate",
    originalPrice: 49900,
    price: 34900,
    iconName: "Cpu",
    tasks: [
      "Implement core data structures",
      "Build algorithm templates",
      "Solve interview sets",
      "Package toolkit",
    ],
    includes: ["Problem sheets", "Template library", "Interview patterns", "Verified certificate"],
    description: "Build strong C++ foundations for coding rounds and system-level problem solving.",
    weeklyTasks: [
      { week: 1, title: "STL + Complexity", type: "Learning", estimatedTime: "4-5 hours", description: "Master STL and time complexity.", steps: ["Vectors/maps", "Sorting", "Binary search", "Complexity analysis"] },
      { week: 2, title: "DSA Modules", type: "Development", estimatedTime: "5-6 hours", description: "Implement trees, graphs, heaps.", steps: ["Trees", "Graphs", "Heaps", "Hashing"] },
      { week: 3, title: "Interview Drills", type: "Practice", estimatedTime: "5-6 hours", description: "Solve curated interview problems.", steps: ["Arrays", "DP", "Greedy", "Backtracking"] },
      { week: 4, title: "Toolkit Finalization", type: "Documentation", estimatedTime: "3-4 hours", description: "Organize reusable C++ toolkit.", steps: ["Refactor", "Commenting", "README", "Submission"] },
    ],
  },
  {
    id: "ml-engineer-internship",
    title: "Machine Learning Engineer Internship",
    projectTitle: "Build Housing Price Predictor",
    domain: "AI / ML",
    duration: "4 Weeks",
    level: "Intermediate",
    originalPrice: 49900,
    price: 34900,
    iconName: "Cpu",
    tasks: [
      "Clean and model datasets",
      "Train regression models",
      "Tune performance",
      "Deploy predictor",
    ],
    includes: ["Jupyter templates", "Model evaluation kit", "Deployment notes", "Verified certificate"],
    description: "Build end-to-end ML pipelines from data prep to model deployment.",
    weeklyTasks: [
      { week: 1, title: "Dataset Pipeline", type: "Analysis", estimatedTime: "4-5 hours", description: "Prepare structured data pipeline.", steps: ["Cleaning", "Feature prep", "Outlier handling", "Split"] },
      { week: 2, title: "Model Training", type: "ML", estimatedTime: "4-5 hours", description: "Train baseline and advanced regressors.", steps: ["Baseline", "Tree models", "Cross-validation", "Metrics"] },
      { week: 3, title: "Optimization", type: "ML", estimatedTime: "4-5 hours", description: "Tune parameters and improve performance.", steps: ["Hyperparameter tuning", "Feature selection", "Error analysis", "Final model"] },
      { week: 4, title: "Serve Model", type: "Deployment", estimatedTime: "3-4 hours", description: "Expose model through API endpoint.", steps: ["Serialize model", "API", "Testing", "Deploy"] },
    ],
  },
  {
    id: "backend-developer-internship",
    title: "Backend Developer Internship",
    projectTitle: "Build E-commerce REST API",
    domain: "Web Development",
    duration: "4 Weeks",
    level: "Intermediate",
    originalPrice: 49900,
    price: 34900,
    iconName: "Database",
    tasks: [
      "Design API architecture",
      "Implement auth and roles",
      "Build orders and payments",
      "Deploy secure backend",
    ],
    includes: ["API specs", "DB schema", "Postman collection", "Verified certificate"],
    description: "Build production-ready backend systems with authentication, payments, and database workflows.",
    weeklyTasks: [
      { week: 1, title: "Schema + API Plan", type: "Backend", estimatedTime: "4-5 hours", description: "Design tables and endpoint contracts.", steps: ["ERD", "Route planning", "Validation schemas", "Seed data"] },
      { week: 2, title: "Core APIs", type: "Backend", estimatedTime: "5-6 hours", description: "Implement products, cart, and orders.", steps: ["CRUD", "Cart flow", "Order flow", "Filters/pagination"] },
      { week: 3, title: "Security + Payments", type: "Integration", estimatedTime: "4-5 hours", description: "Add auth, RBAC, and payment gateway.", steps: ["JWT", "Role guards", "Razorpay", "Webhook handling"] },
      { week: 4, title: "Deploy + Monitoring", type: "Deployment", estimatedTime: "3-4 hours", description: "Deploy and monitor service.", steps: ["Deployment", "Env config", "Logs", "Health checks"] },
    ],
  },
  {
    id: "data-analytics-internship",
    title: "Data Analytics Internship",
    projectTitle: "Build Sales Insights Dashboard",
    domain: "Data Science",
    duration: "4 Weeks",
    level: "Beginner Friendly",
    originalPrice: 49900,
    price: 34900,
    iconName: "Database",
    tasks: [
      "Process raw corporate dataset",
      "Develop visualization dashboard",
      "Translate data into business insights",
    ],
    includes: ["Starter dataset", "Dashboard guidance", "Verified certificate"],
    description: "Build practical dashboards and communicate insights clearly for decision-making.",
    weeklyTasks: [
      { week: 1, title: "Data Preparation", type: "Analysis", estimatedTime: "3-4 hours", description: "Clean and structure CSV/Excel data for analysis.", steps: ["Import dataset", "Handle missing values", "Create baseline metrics", "Data quality checks"], resources: ["Statistical analysis foundations"], example: "Clean analytical dataset" },
      { week: 2, title: "Easy Project Build", type: "Visualization", estimatedTime: "3-4 hours", description: "Build Excel/CSV dashboard with key KPI views.", steps: ["KPI selection", "Chart setup", "Dashboard layout", "Formatting standards"], resources: ["Data visualization best practices"], example: "Basic KPI dashboard" },
      { week: 3, title: "Medium Project Build", type: "Visualization", estimatedTime: "3-4 hours", description: "Create interactive dashboard with filters and drill-down.", steps: ["Filter controls", "Dynamic charts", "Comparative views", "Usability checks"], resources: ["Dashboard design guide"], example: "Interactive dashboard" },
      { week: 4, title: "Insights Presentation", type: "Documentation", estimatedTime: "2-3 hours", description: "Convert analysis into decision-ready business summary.", steps: ["Insight extraction", "Recommendation writing", "Executive memo", "Presentation prep"], resources: ["Executive communication guidelines"], example: "Decision-focused report" },
    ],
  },
  {
    id: "power-bi-data-analyst-internship",
    title: "Power BI Data Analyst Internship",
    projectTitle: "Build Executive KPI Dashboard in Power BI",
    domain: "Data Science",
    duration: "4 Weeks",
    level: "Beginner Friendly",
    originalPrice: 49900,
    price: 34900,
    iconName: "Database",
    tasks: [
      "Connect and clean raw datasets",
      "Build interactive KPI dashboards",
      "Create DAX-based metrics",
      "Publish and share reports",
    ],
    includes: ["Power BI templates", "Dataset pack", "Mentor checkpoints", "Verified certificate"],
    description: "Learn practical analytics by building job-ready dashboards in Power BI.",
    weeklyTasks: [
      { week: 1, title: "Data Modeling Basics", type: "Analysis", estimatedTime: "4-5 hours", description: "Import data and design model relationships.", steps: ["Import files", "Clean columns", "Define relationships", "Create calendar table"] },
      { week: 2, title: "Dashboard Design", type: "Visualization", estimatedTime: "4-5 hours", description: "Build KPI cards, charts, and filters.", steps: ["KPI cards", "Trend charts", "Slicers", "Layout polish"] },
      { week: 3, title: "DAX Measures", type: "Analytics", estimatedTime: "4-5 hours", description: "Create reusable DAX calculations.", steps: ["Measure basics", "Time-intelligence", "Performance checks", "Validation"] },
      { week: 4, title: "Publish & Present", type: "Deployment", estimatedTime: "3-4 hours", description: "Publish report and create insight summary.", steps: ["Publish", "Share permissions", "Insight deck", "Final walkthrough"] },
    ],
  },
  {
    id: "tableau-visionary-internship",
    title: "Tableau Visionary Internship",
    projectTitle: "Build Interactive Business Storyboard in Tableau",
    domain: "Data Science",
    duration: "4 Weeks",
    level: "Beginner Friendly",
    originalPrice: 49900,
    price: 34900,
    iconName: "LineChart",
    tasks: [
      "Create Tableau dashboards",
      "Design business storyboards",
      "Use calculated fields",
      "Present insights clearly",
    ],
    includes: ["Tableau workbook templates", "Practice datasets", "Review support", "Verified certificate"],
    description: "Turn raw datasets into visual stories with Tableau dashboards used in industry.",
    weeklyTasks: [
      { week: 1, title: "Tableau Fundamentals", type: "Learning", estimatedTime: "4-5 hours", description: "Set up workbook and connect data sources.", steps: ["Connect data", "Data types", "Basic charts", "Sorting/filtering"] },
      { week: 2, title: "Dashboard Assembly", type: "Visualization", estimatedTime: "4-5 hours", description: "Build dashboard views and interactions.", steps: ["Chart selection", "Action filters", "Dashboard layout", "Mobile view"] },
      { week: 3, title: "Calculated Insights", type: "Analytics", estimatedTime: "4-5 hours", description: "Use calculated fields and parameters.", steps: ["Calculated fields", "Parameters", "Scenario analysis", "KPI logic"] },
      { week: 4, title: "Business Storytelling", type: "Presentation", estimatedTime: "3-4 hours", description: "Present analysis as a business story.", steps: ["Storyboard", "Narrative flow", "Executive summary", "Final demo"] },
    ],
  },
  {
    id: "data-science-python-internship",
    title: "Data Science with Python Internship",
    projectTitle: "Build Customer Churn Prediction Model",
    domain: "Python",
    duration: "4 Weeks",
    level: "Intermediate",
    originalPrice: 49900,
    price: 34900,
    iconName: "Cpu",
    tasks: [
      "Clean and explore datasets",
      "Train classification model",
      "Evaluate model performance",
      "Deploy prediction API",
    ],
    includes: ["Python notebooks", "Model templates", "Deployment support", "Verified certificate"],
    description: "Apply Python data science workflows end-to-end on real business problems.",
    weeklyTasks: [
      { week: 1, title: "EDA with Python", type: "Analysis", estimatedTime: "4-5 hours", description: "Perform exploratory analysis with pandas and seaborn.", steps: ["Load data", "Clean missing values", "Visual EDA", "Feature ideas"] },
      { week: 2, title: "Model Building", type: "ML", estimatedTime: "4-5 hours", description: "Train baseline and advanced classifiers.", steps: ["Baseline model", "Train/test split", "Tuning", "Comparison"] },
      { week: 3, title: "Model Validation", type: "Analytics", estimatedTime: "4-5 hours", description: "Evaluate precision, recall, and ROC metrics.", steps: ["Confusion matrix", "ROC AUC", "Error analysis", "Model selection"] },
      { week: 4, title: "API Deployment", type: "Deployment", estimatedTime: "3-4 hours", description: "Serve model as an API endpoint.", steps: ["Serialize model", "Create endpoint", "Deploy", "Smoke test"] },
    ],
  },
  {
    id: "data-science-r-master-internship",
    title: "Data Science with R Master Internship",
    projectTitle: "Build Forecasting Model with R",
    domain: "Data Science",
    duration: "4 Weeks",
    level: "Intermediate",
    originalPrice: 49900,
    price: 34900,
    iconName: "LineChart",
    tasks: [
      "Perform R-based data wrangling",
      "Build statistical models",
      "Create ggplot2 dashboards",
      "Generate forecast reports",
    ],
    includes: ["R scripts", "Practice data", "Mentor review", "Verified certificate"],
    description: "Master practical R workflows for analytics and forecasting projects.",
    weeklyTasks: [
      { week: 1, title: "R Workflow Setup", type: "Learning", estimatedTime: "4-5 hours", description: "Set up tidyverse workflow and data prep.", steps: ["RStudio setup", "Data import", "dplyr transforms", "Quality checks"] },
      { week: 2, title: "Statistical Modeling", type: "Analytics", estimatedTime: "4-5 hours", description: "Build regression and classification models.", steps: ["Model selection", "Train", "Assumption checks", "Interpretation"] },
      { week: 3, title: "Visualization", type: "Visualization", estimatedTime: "4-5 hours", description: "Design insights with ggplot2 visuals.", steps: ["Plot types", "Theming", "Story visuals", "Dashboard export"] },
      { week: 4, title: "Forecast Report", type: "Presentation", estimatedTime: "3-4 hours", description: "Create business forecasting report.", steps: ["Forecast model", "Backtesting", "Recommendation", "Final presentation"] },
    ],
  },
  {
    id: "business-analytics-r-internship",
    title: "Business Analytics with R Internship",
    projectTitle: "Build Business Performance Analytics Model",
    domain: "Data Science",
    duration: "4 Weeks",
    level: "Beginner Friendly",
    originalPrice: 49900,
    price: 34900,
    iconName: "Database",
    tasks: [
      "Analyze business KPIs in R",
      "Build profitability dashboards",
      "Find actionable trends",
      "Deliver executive insights",
    ],
    includes: ["KPI templates", "R code packs", "Business case guide", "Verified certificate"],
    description: "Translate business data into clear decisions using analytics and R-based reporting.",
    weeklyTasks: [
      { week: 1, title: "KPI Foundations", type: "Analysis", estimatedTime: "4-5 hours", description: "Define and calculate core business KPIs.", steps: ["Revenue KPIs", "Cost KPIs", "Cohort setup", "Baseline"] },
      { week: 2, title: "Analytics Modeling", type: "Analytics", estimatedTime: "4-5 hours", description: "Build models for trend and variance analysis.", steps: ["Trend analysis", "Variance split", "Segment study", "Findings"] },
      { week: 3, title: "Dashboarding", type: "Visualization", estimatedTime: "4-5 hours", description: "Create management-ready dashboards.", steps: ["Dashboard design", "KPI cards", "Filters", "Narrative"] },
      { week: 4, title: "Executive Deck", type: "Presentation", estimatedTime: "3-4 hours", description: "Present recommendations to stakeholders.", steps: ["Summary", "Insights", "Recommendations", "Roadmap"] },
    ],
  },
];

export const faqs = [
  { question: "Do I need any experience?", answer: "No. All programs are beginner-friendly and designed for students with no prior experience." },
  { question: "When can I start?", answer: "Immediately after enrollment. Work at your own pace within the program duration." },
  { question: "Can employers verify my certificate?", answer: "Yes. Every certificate has a unique ID that can be verified at skillbridge.in/verify." },
  { question: "How much time does it take?", answer: "About 2-4 hours per week. Tasks are flexible and fit around your college schedule." },
  { question: "What if I get stuck?", answer: "Every task includes clear instructions and resources. You can also raise a support ticket from your dashboard." },
];

export const reviews = [
  { name: "Siddharth Menon", college: "IIT Madras", text: "The structured approach mimics real corporate environments perfectly. Highly recommended.", rating: 5 },
  { name: "Aanya Gupta", college: "Delhi University", text: "Professional workflows and excellent documentation provided a solid foundation.", rating: 5 },
  { name: "Rohan Desai", college: "VJTI Mumbai", text: "Clear task progression resulting in a verifiable output for my professional profile.", rating: 4 },
];

export const certificates = [
  { id: "SB-2026-7842", studentName: "Aarav Sharma", college: "IIT Delhi", internship: "Digital Marketing", issueDate: "12 April 2026", status: "Verified" },
  { id: "SB-2026-9011", studentName: "Neha Verma", college: "NIT Trichy", internship: "Web Development", issueDate: "08 April 2026", status: "Verified" },
  { id: "SB-2026-3487", studentName: "Priya Reddy", college: "BITS Pilani", internship: "Data Analytics", issueDate: "10 April 2026", status: "Verified" },
];

export function getInternshipById(id: string) {
  return internships.find((internship) => internship.id === id);
}

export function getCertificateById(id: string) {
  return certificates.find((certificate) => certificate.id.toUpperCase() === id.toUpperCase());
}
